version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${LOCAL_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_PORT: 9092 # necessary for KAFKA_CREATE_TOPICS to work
      KAFKA_CREATE_TOPICS: "com.halodoc.timor.productPacakge.v1.product_package:1:1"